<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\index.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\kotik.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\404.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\404.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\about.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\all-game.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-details.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-details-left-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-details-right-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-grid-left-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-grid-right-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-grid-without-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-left-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-right-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\blog-without-sidebar.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\contact.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\faq.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\game-details.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\index.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\match.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\match-details.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\player-details.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\players.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mime-types.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\satisfactory.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\48px-Lizard_Doggo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\48px-Satisfactory_logo_full_color_square.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\100px-Coal-Powered_Generator.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\100px-Hard_Drive.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\100px-Lizard_Doggo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\100px-MAM.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\100px-Power_Line.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\100px-Space_Elevator.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\300px-Update1.2_Sign_Logo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\CC-BY-NC-SA_footer_badge.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\database_icon.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Discord.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Epic_Games.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Facebook.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\file_icon.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Humble.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Instagram.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\LEADERBOARD.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\LEADERBOARD.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\link_icon.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\main_box_texture.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\MediaWiki_footer_badge.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Network_footer_badge.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Network_header_logo.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Network_indiedeals_logo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Reddit.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\satellite.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Site-background-light.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Site-logo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\star_icon.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Steam.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\TikTok.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\Twitch.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\video.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\X.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory\media\images\YouTube.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\Search.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\search-01.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\chatgpt.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\deepseek.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\geeksforgeeks.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\github.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\linkedin.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\plus-sign.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search\icons\youtube.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\media\footerLogo_valve_new.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\media\header_logo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\media\logo_steam.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\media\qr.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\steam.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\mail.php">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\blog\_blog-details.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\blog\_blog-grid-style.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\blog\_blog-list-style.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_about.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_blog.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_contact.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_faq.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_footer.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_game-details.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_header.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_match-details.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_other.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_payer-details.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\section\_player-list.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\_common.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\_variabls.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\scss\style.scss">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\vendor\bootstrap.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\vendor\jquery-3.6.0.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\vendor\jquery-migrate-3.3.2.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\vendor\modernizr-3.7.1.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\vendor\popper.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\ajax-mail.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\jquery-waypoints.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\jquery.counterup.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\jquery.magnific-popup.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\jquery.nice-select.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\mailchimp-ajax.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\main.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\slick.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\js\wow.min.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\body-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\body-bg2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\breadcrumbs-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\gaming-bg1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\gaming-update.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\hero-banner-shape.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\hero-bg1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\bg\hero-position-img.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-grid-1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-grid-2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-grid-3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-grid-4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-grid-5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-grid-6.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-like-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-related-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-sidebar-thumb.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog-sticky.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog6.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog7.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog8.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog9.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\blog_details_layer.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\comment2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\post-comment1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\post-comment2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\blog\post-comment3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\arrrow-icon.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\arrrow-icon2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\arrrow-left-icon.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\dribble.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\email.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\facebook-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\location.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\navigation-arrow1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\navigation-arrow2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\navigation-bg1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\navigation-bg2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\navigation-bg3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\navigation-bg4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\owl.video.play.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\phone.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\reply.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\scroll-top.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\twittre.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\icon\youtobe-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\Icon metro-list.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\Icon open-grid-three-up.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\logo\logo.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\404.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\about-thumb.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\breadcrumbs-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\btn-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\btn-signup.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\contact-form-bg-shape.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\counter-position-icon.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\dot-button.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\game-details-thumb.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\game-vs1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\game-vs2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\game-vs3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\gaming-world-bg1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\gaming-world-bg2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\gaming-world-bg3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\gaming-world1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\gaming-world2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\gaming-world3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\icon.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\menu_shape.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\meta-img1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\meta-img2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\meta-img3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\paypal.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\play-btn.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\play-btn2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\play-btn3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\player-bg-maskot.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\players1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\players2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\players3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\players4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\players5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\players6.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\popular-game-thumb1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\popular-game-thumb2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\popular-game-thumb3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\popular-game-thumb4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\popular-game-thumb5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\tam-text-shape.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\tam-text-shape2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\team1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\team2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\team3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\testimonial-bg.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\testimonial-bg-fullwidth.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\testimonial-thumb.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\text-mini-shape.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb6.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb7.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb8.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb9.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\upcoming-game-thumb10.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\video-play.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\winners1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\winners2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\winners3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\winners4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\winners5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\others\winners6.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\details\player-details-img.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\list\player-1.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\list\player-2.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\list\player-3.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\list\player-4.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\list\player-5.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\player\list\player-6.webp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\img\favicon.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\Big Space.otf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\Big Space.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\icofont.eot">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\icofont.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\icofont.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\icofont.woff">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\fonts\icofont.woff2">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\animate.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\icofont.min.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\magnific-popup.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\nice-select.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\slick.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\style.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\bonx\assets\css\vendor\bootstrap.min.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Framework\Settings\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Framework\Core\HttpServer.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Compile>
    </ItemGroup>

</Project>
